<?php

$systemDocumentation = <<<DOC
You are an expert CounterStrikeSharp (CS2) developer.
General CS2 API Knowledge Base:
- Base class: BasePlugin
- Events: RegisterEventHandler<EventPlayerDeath>, RegisterEventHandler<EventPlayerConnectFull>, etc.
- Hook handler signature: HookResult OnEventName(EventName @event, GameEventInfo info)
- Event properties: @event.Userid (victim), @event.Attacker (attacker), @event.Weapon (weapon name string), @event.Headshot (bool)
- Player entity validation: player != null && player.IsValid && !player.IsBot && player.PlayerPawn?.Value != null
- Giving items: player.GiveNamedItem("weapon_name")
- Modifying HP: player.PlayerPawn.Value.Health = newValue; Utilities.SetStateChanged(player.PlayerPawn.Value, "CBaseEntity", "m_iHealth");
- Centered HTML alert: player.PrintToCenterHtml(htmlString)
- Colored chat: player.PrintToChat($" {ChatColors.Red}...")
- Playing sound events: player.ExecuteClientCommand($"play {soundPath}")

Generate valid, idiomatic C# code for the requested plugin without any placeholders. Return ONLY C# code.
DOC;

$complexUserPrompt = "Create a Vampire Knife plugin: When an attacker kills a victim with any knife (weapon string contains 'knife' or 'bayonet'), give the attacker +30 HP (clamp maximum health to 120 HP), give them a smoke grenade ('weapon_smokegrenade'), play client sound 'sounds/ambient/creatures/crow_01.vsnd', and show centered HTML alert '<font color=\'red\'><b>🩸 ВАМПИРИЗМ! +30 HP</b></font>'.";

$payload = json_encode([
    'model' => 'qwen3-14b-tools:latest',
    'system' => $systemDocumentation,
    'prompt' => $complexUserPrompt,
    'stream' => false,
    'options' => [
        'temperature' => 0.2,
    ]
]);

$ch = curl_init('http://127.0.0.1:11434/api/generate');
curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type:application/json']);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_TIMEOUT, 90);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Curl error: ' . curl_error($ch);
} else {
    $json = json_decode($result, true);
    echo "=== GENERATED BY QWEN3-14B FOR COMPLEX CUSTOM LOGIC ===\n";
    echo $json['response'] ?? 'No response';
}
curl_close($ch);
