<?php

$systemPrompt = <<<PROMPT
You are a professional Counter-Strike 2 (CS2) plugin developer specialized in CounterStrikeSharp (CSS API v250+).

CRITICAL CS2 COUNTERSTRIKESHARP RULES:
1. Always inherit from `BasePlugin`.
2. Do NOT use fake classes like `CsPlugin`, `GetPlayers()`, `SendChatMessage`, or `SetAttribute`.
3. Override properties:
   public override string ModuleName => "VipPerk";
   public override string ModuleVersion => "1.0.0";
   public override string ModuleAuthor => "CS2 Visual Studio";
4. Register events inside `public override void Load(bool hotReload)`:
   RegisterEventHandler<EventRoundStart>(OnRoundStart);
   RegisterEventHandler<EventPlayerDeath>(OnPlayerDeath);
5. Event handlers MUST return `HookResult.Continue`.
6. To iterate online human players:
   Utilities.GetPlayers().Where(p => p != null && p.IsValid && !p.IsBot && p.PlayerPawn?.Value != null)
7. To check permissions:
   AdminManager.PlayerHasPermissions(player, "@css/vip")
8. To modify player health:
   player.PlayerPawn.Value.Health += 50;
   Utilities.SetStateChanged(player.PlayerPawn.Value, "CBaseEntity", "m_iHealth");
9. To print colored chat:
   player.PrintToChat($" {ChatColors.Green}[VIP]{ChatColors.White} You received +50 HP!");
10. Include all required namespaces:
   using System;
   using System.Linq;
   using CounterStrikeSharp.API;
   using CounterStrikeSharp.API.Core;
   using CounterStrikeSharp.API.Core.Attributes;
   using CounterStrikeSharp.API.Modules.Admin;
   using CounterStrikeSharp.API.Modules.Utils;

Return ONLY the complete C# code without any markdown explanations.
PROMPT;

$userPrompt = "Create a VIP perk where players with @css/vip get +50 HP and a green chat message on round start.";

$payload = json_encode([
    'model' => 'qwen3-14b-tools:latest',
    'system' => $systemPrompt,
    'prompt' => $userPrompt,
    'stream' => false,
    'options' => [
        'temperature' => 0.1,
    ]
]);

$ch = curl_init('http://127.0.0.1:11434/api/generate');
curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type:application/json']);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_TIMEOUT, 90);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Curl error: ' . curl_error($ch);
} else {
    $json = json_decode($result, true);
    echo "=== GENERATED BY QWEN3-14B-TOOLS (WITH ACCURATE CS2 SYSTEM CONTEXT) ===\n";
    echo $json['response'] ?? 'No response field';
}
curl_close($ch);
